### PR TITLE
[#114052695] Added new dts for 702 board, and DCC for both.

### PR DESCRIPTION
**Pull request by alxn**
Trying to enable the `hvc0` TTY... as well as keep the ethernet alive on the 702 board.

### CODE REVIEW

**Comment by sbelair** [comment]
@alxn looks good- please merge

**Comment by alxn** [comment]
This added in https://github.com/torvalds/linux/commit/16c63f8ea49c3fcb9eac7ebc511f5c821d3c55c2

**Comment by alxn** [comment]
@sbelair @mishka99 is booting somewhat:

```
Starting kernel ...


Booting Linux on physical CPU 0x0
Linux version 4.0.0-xckts-00003-ged40d582-dirty (alun@poweredge.xockets.com) (gcc version 4.9.2 (S
ourcery CodeBench Lite 2015.05-17) ) #7 SMP PREEMPT Thu Feb 18 15:57:17 PST 2016
CPU: ARMv7 Processor [413fc090] revision 0 (ARMv7), cr=18c5387d
CPU: PIPT / VIPT nonaliasing data cache, VIPT aliasing instruction cache
Machine model: Zynq ZC702 Development Board, running Xockets PL
cma: Reserved 16 MiB at 0x1cc00000
Memory policy: Data cache writealloc
PERCPU: Embedded 11 pages/cpu @dfbd0000 s12672 r8192 d24192 u45056
Built 1 zonelists in Zone order, mobility grouping on.  Total pages: 130048
Kernel command line: console=hvc0,115200 root=/dev/ram rw earlyprintk
PID hash table entries: 2048 (order: 1, 8192 bytes)
Dentry cache hash table entries: 65536 (order: 6, 262144 bytes)
Inode-cache hash table entries: 32768 (order: 5, 131072 bytes)
Memory: 472544K/524288K available (4623K kernel code, 218K rwdata, 1648K rodata, 216K init, 201K bss, 35360K reserved, 16384K cma-reserved, 0K highmem)
Virtual kernel memory layout:
    vector  : 0xffff0000 - 0xffff1000   (   4 kB)
    fixmap  : 0xffc00000 - 0xfff00000   (3072 kB)
    vmalloc : 0xe0800000 - 0xff000000   ( 488 MB)
    lowmem  : 0xc0000000 - 0xe0000000   ( 512 MB)
    pkmap   : 0xbfe00000 - 0xc0000000   (   2 MB)
    modules : 0xbf000000 - 0xbfe00000   (  14 MB)
      .text : 0xc0008000 - 0xc0627f44   (6272 kB)
      .init : 0xc0628000 - 0xc065e000   ( 216 kB)
      .data : 0xc065e000 - 0xc06948e0   ( 219 kB)
       .bss : 0xc06948e0 - 0xc06c6e34   ( 202 kB)
Preemptible hierarchical RCU implementation.
        Additional per-CPU info printed with stalls.
        RCU restricting CPUs from NR_CPUS=4 to nr_cpu_ids=2.
RCU: Adjusting geometry for rcu_fanout_leaf=16, nr_cpu_ids=2
NR_IRQS:16 nr_irqs:16 16
L2C: platform modifies aux control register: 0x02060000 -> 0x32460000
L2C: DT/platform modifies aux control register: 0x02060000 -> 0x32460000
L2C-310 erratum 769419 enabled
L2C-310 enabling early BRESP for Cortex-A9
L2C-310 full line of zeros enabled for Cortex-A9
L2C-310 ID prefetch enabled, offset 1 lines
L2C-310 dynamic clock gating enabled, standby mode enabled
L2C-310 cache controller enabled, 8 ways, 512 kB
L2C-310: CACHE_ID 0x410000c8, AUX_CTRL 0x76460001
slcr mapped to e0804000
zynq_clock_init: clkc starts at e0804100
Zynq clock init
sched_clock: 64 bits at 333MHz, resolution 3ns, wraps every 3298534883328ns
timer #0 at e0808000, irq=17
Console: colour dummy device 80x30
console [hvc0] enabled
Calibrating delay loop... 1332.01 BogoMIPS (lpj=6660096)
pid_max: default: 32768 minimum: 301
Mount-cache hash table entries: 1024 (order: 0, 4096 bytes)
Mountpoint-cache hash table entries: 1024 (order: 0, 4096 bytes)
CPU: Testing write buffer coherency: ok
CPU0: thread -1, cpu 0, socket 0, mpidr 80000000
Setting up static identity map for 0x460a70 - 0x460ac8
CPU1: thread -1, cpu 1, socket 0, mpidr 80000001
Brought up 2 CPUs
SMP: Total of 2 processors activated (2664.03 BogoMIPS).
CPU: All CPU(s) started in SVC mode.
```

**Comment by sbelair** [comment]
Excellent! Are there issues with the rootfs? Also, does this uImage have
Misha's OCM kernel module?

On Thu, Feb 18, 2016 at 4:25 PM, Alun Evans notifications@github.com
wrote:

> @sbelair https://github.com/sbelair @mishka99
> https://github.com/mishka99 is booting somewhat:
> 
> Starting kernel ...
> 
> Booting Linux on physical CPU 0x0
> Linux version 4.0.0-xckts-00003-ged40d582-dirty (alun@poweredge.xockets.com) (gcc version 4.9.2 (S
> ourcery CodeBench Lite 2015.05-17) ) #7 SMP PREEMPT Thu Feb 18 15:57:17 PST 2016
> CPU: ARMv7 Processor [413fc090] revision 0 (ARMv7), cr=18c5387d
> CPU: PIPT / VIPT nonaliasing data cache, VIPT aliasing instruction cache
> Machine model: Zynq ZC702 Development Board, running Xockets PL
> cma: Reserved 16 MiB at 0x1cc00000
> Memory policy: Data cache writealloc
> PERCPU: Embedded 11 pages/cpu @dfbd0000 s12672 r8192 d24192 u45056
> Built 1 zonelists in Zone order, mobility grouping on.  Total pages: 130048
> Kernel command line: console=hvc0,115200 root=/dev/ram rw earlyprintk
> PID hash table entries: 2048 (order: 1, 8192 bytes)
> Dentry cache hash table entries: 65536 (order: 6, 262144 bytes)
> Inode-cache hash table entries: 32768 (order: 5, 131072 bytes)
> Memory: 472544K/524288K available (4623K kernel code, 218K rwdata, 1648K rodata, 216K init, 201K bss, 35360K reserved, 16384K cma-reserved, 0K highmem)
> Virtual kernel memory layout:
>     vector  : 0xffff0000 - 0xffff1000   (   4 kB)
>     fixmap  : 0xffc00000 - 0xfff00000   (3072 kB)
>     vmalloc : 0xe0800000 - 0xff000000   ( 488 MB)
>     lowmem  : 0xc0000000 - 0xe0000000   ( 512 MB)
>     pkmap   : 0xbfe00000 - 0xc0000000   (   2 MB)
>     modules : 0xbf000000 - 0xbfe00000   (  14 MB)
>       .text : 0xc0008000 - 0xc0627f44   (6272 kB)
>       .init : 0xc0628000 - 0xc065e000   ( 216 kB)
>       .data : 0xc065e000 - 0xc06948e0   ( 219 kB)
>        .bss : 0xc06948e0 - 0xc06c6e34   ( 202 kB)
> Preemptible hierarchical RCU implementation.
>         Additional per-CPU info printed with stalls.
>         RCU restricting CPUs from NR_CPUS=4 to nr_cpu_ids=2.
> RCU: Adjusting geometry for rcu_fanout_leaf=16, nr_cpu_ids=2
> NR_IRQS:16 nr_irqs:16 16
> L2C: platform modifies aux control register: 0x02060000 -> 0x32460000
> L2C: DT/platform modifies aux control register: 0x02060000 -> 0x32460000
> L2C-310 erratum 769419 enabled
> L2C-310 enabling early BRESP for Cortex-A9
> L2C-310 full line of zeros enabled for Cortex-A9
> L2C-310 ID prefetch enabled, offset 1 lines
> L2C-310 dynamic clock gating enabled, standby mode enabled
> L2C-310 cache controller enabled, 8 ways, 512 kB
> L2C-310: CACHE_ID 0x410000c8, AUX_CTRL 0x76460001
> slcr mapped to e0804000
> zynq_clock_init: clkc starts at e0804100
> Zynq clock init
> sched_clock: 64 bits at 333MHz, resolution 3ns, wraps every 3298534883328ns
> timer #0 at e0808000, irq=17
> Console: colour dummy device 80x30
> console [hvc0] enabled
> Calibrating delay loop... 1332.01 BogoMIPS (lpj=6660096)
> pid_max: default: 32768 minimum: 301
> Mount-cache hash table entries: 1024 (order: 0, 4096 bytes)
> Mountpoint-cache hash table entries: 1024 (order: 0, 4096 bytes)
> CPU: Testing write buffer coherency: ok
> CPU0: thread -1, cpu 0, socket 0, mpidr 80000000
> Setting up static identity map for 0x460a70 - 0x460ac8
> CPU1: thread -1, cpu 1, socket 0, mpidr 80000001
> Brought up 2 CPUs
> SMP: Total of 2 processors activated (2664.03 BogoMIPS).
> CPU: All CPU(s) started in SVC mode.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Xockets/linux-xlnx/pull/3#issuecomment-185991067.

## 

Stephen Belair
408-655-6358
Xockets, Inc. http://xockets.com

**Comment by alxn** [comment]
@sbelair Maybe rootfs problem, or later stage in kernel - this is the Ximm though, so no OCM module?

**Pull request merged**
