### PR TITLE
[#99161324] Added Xockets Zynq dts and config.

### PR DESCRIPTION
**Pull request by alxn**
Added a basic device tree for the zynq, with the request memory size.

Staged a new config file, an exact copy of `xilinx_zynq_defconfig` for now.

### CODE REVIEW

**Comment by alxn** [comment]
@mishka99 fyi

**Comment by sbelair** [comment]
@alxn- did you want to add an entry to the dts file to expand the root fs size, or wait until we know how much space we need? These changes look good otherwise- check in at will.

**Comment by alxn** [comment]
@sbelair the root fs size should come from the genextfs, not the `ramdisk_size` kernel option, I was just about to open a different ticket for that (i.e. that would only be in `SW/ximm/build/Makefile`).

Question for @mishka99 really, looking at [this](http://opensource.dyc.edu/ramdisk-vs-ramfs) info, I'm pretty sure I have a `initramfs`, **not** a `initrd`, and not a bootstrapped to `tmpfs`. This is what I see on the existing Zynq:

```
[root@zynq01 /root]# df -h
Filesystem                Size      Used Available Use% Mounted on
/dev/root               253.8M     49.5M    191.5M  21% /
devtmpfs                373.1M         0    373.1M   0% /dev
none                    392.6M         0    392.6M   0% /tmp
/dev/mmcblk0p1            7.4G    109.0M      7.3G   1% /mnt/sdcard
[root@zynq01 /root]# free -m
             total         used         free       shared      buffers
Mem:           785          275          509            0            1
-/+ buffers:                274          510
Swap:            0            0            0
[root@zynq01 /root]# 
```

And since I'm doing `--size-in-blocks 262144`, i.e. `262144/1024` is 256MB, that looks like what I've got here. If anything, we need to shrink this number, but I'll do that in another ticket.

**Comment by mishka99** [comment]
Actually it's an initrd - we may want to check into converting it into initramfs.
If zynq03 dmesg doesn't lie:
Trying to unpack rootfs image as initramfs...
rootfs image is not initramfs (no cpio magic); looks like an initrd
0x000000620000-0x000000c00000 : "qspi-rootfs"
VFS: Mounted root (ext2 filesystem) on device 1:0.

**Comment by mishka99** [comment]
This is from /proc/config.gz (via zcat)
CONFIG_INITRAMFS_SOURCE=""
CONFIG_BLK_DEV_RAM=y
CONFIG_BLK_DEV_RAM_COUNT=16
CONFIG_BLK_DEV_RAM_SIZE=16384

**Comment by alxn** [comment]
@mishka99 ok glad I checked. Have you hacked around with this all before?

**Comment by mishka99** [comment]
Yeah but a while back and my memory cache is cleared of all that :)  So a cache refill from google and kernel documentation would be needed :)

**Comment by alxn** [comment]
@mishka99 so I've spent 2 days now battling that I didn't fix this correctly last time... :dizzy_face::gun:

**Pull request merged**
